### ISSUE TITLE
Support Redis Sentinel mode

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/harbor-scanner-trivy#102]
https://redis.io/topics/sentinel

Harbor can be deployed in HA environment where Redis is also available in Sentinel mode. We should be able to support such setup.

The task here is to check what are the requirements to support sentinel mode and whether the https://github.com/gomodule/redigo lib is suitable. Then, implement the changes to the connection pool and config.

This is relevant for the integration with https://github.com/goharbor/harbor-operator and https://github.com/goharbor/harbor-cluster-operator

**Comment by bitsf** [comment]
Hi @danielpacak 
I would like to make the env in harbor configured as

- for in cluster redis
  `SCANNER_STORE_REDIS_URL=redis://redis:6379/5`
- for sentinel redis
  `SCANNER_STORE_REDIS_URL=redis+sentinel://redis-cluster_sentinel_1:26379,redis-cluster_sentinel_2:26379,redis-cluster_sentinel_3:26379/mymaster/5`

Is that OK?

**Comment by danielpacak** [comment]
> Hi @danielpacak
> I would like to make the env in harbor configured as
> 
> * for in cluster redis
>   `SCANNER_STORE_REDIS_URL=redis://redis:6379/5`
> * for sentinel redis
>   `SCANNER_STORE_REDIS_URL=redis+sentinel://redis-cluster_sentinel_1:26379,redis-cluster_sentinel_2:26379,redis-cluster_sentinel_3:26379/mymaster/5`
> 
> Is that OK?

Hi @bitsf . Yes, I think we can support such URL schema

**Comment by hrist0stoichev** [comment]
I was trying to implement Redis Sentinel support for `harbor-scanner-trivy` for quite some time but there isn't a good library that can be readily used. `harbor-scanner-trivy` uses `redigo`, which itself doesn't provide Sentinel support. [Sentinel](https://github.com/FZambia/sentinel) is a library that is an extension to `redigo` for Sentinel support but it implements the protocol described [here](https://redis.io/topics/sentinel-clients) only partially. What I mean is that the library manages to identify the master and read from/write to it. In case of a failover, the new master is also identified properly. Yet, the library doesn't make use of the slaves. All queries are sent to the master (both read and write), as opposed to writing only to master and load balancing the read queries to the slaves.

**Comment by danielpacak** [comment]
> I was trying to implement Redis Sentinel support for `harbor-scanner-trivy` for quite some time but there isn't a good library that can be readily used. `harbor-scanner-trivy` uses `redigo`, which itself doesn't provide Sentinel support. [Sentinel](https://github.com/FZambia/sentinel) is a library that is an extension to `redigo` for Sentinel support but it implements the protocol described [here](https://redis.io/topics/sentinel-clients) only partially. What I mean is that the library manages to identify the master and read from/write to it. In case of a failover, the new master is also identified properly. Yet, the library doesn't make use of the slaves. All queries are sent to the master (both read and write), as opposed to writing only to master and load balancing the read queries to the slaves.

That's great feedback @hrist0stoichev Do you happen to know if this one https://github.com/go-redis/redis has by any chance a better support for Sentinel?

**Comment by hrist0stoichev** [comment]
To be honest @danielpacak, I don't really know whether it has better support. When I researched this, I saw that it has native support for Sentinel but I haven't really looked at the implementation because `harbor-scanner-trivy` already uses `redigo`. I will take a quick look and update if anything comes up!
