### ISSUE TITLE
CVE discrepancy 

### ISSUE THREAD

**Issue by piyush94** [aquasecurity/harbor-scanner-trivy#113]
Hi,
After updating to harbor-scanner-trivy v0.10.0, we are seeing a sharp difference in the CVE report and count. Earlier we were running on v0.9.0.
Does this scanner internally use trivy?
From the commit history i could make out 0.9.0 was using trivy 0.6.0 and now it's using 0.7.0.
Some tests i ran:
**trivy 0.6.0**:
![trivy0 6 0](https://user-images.githubusercontent.com/11614204/82550417-1ba0e280-9b7c-11ea-9dc3-1825b73370af.JPG)

**trivy 0.7.0**:
![trivy0 7 0](https://user-images.githubusercontent.com/11614204/82550443-278ca480-9b7c-11ea-8dde-139be6d53166.JPG)

As you can see there is a difference in the individual counts, although vuln DB is the same.

CC: @svisagan83

**Comment by knqyf263** [comment]
Hi @piyush94, I'm a developer of Trivy. We changed the behavior of severity in v0.7.0. v0.6.0 used the severity from NVD, but v0.7.0 uses the severity from a vendor such as Red Hat and Debian. The NVD severity is the generic one, but the vendor provides more accurate severity.
https://github.com/aquasecurity/trivy/releases/tag/v0.7.0

**Comment by danielpacak** [comment]
@piyush94 I should have mentioned the change in the release notes https://github.com/aquasecurity/harbor-scanner-trivy/releases/tag/v0.10.0, which are now updated.

Please close the ticket if we answered your questions.

**Comment by piyush94** [comment]
@danielpacak, @knqyf263 - Thanks. This was helpful.
