### ISSUE TITLE
CVE duplication in scanning result

### ISSUE THREAD

**Issue by piyush94** [aquasecurity/harbor-scanner-trivy#114]
Hi,

We are seeing below duplications in the scan results. And also a discrepancy between scans done short intervals apart. These two were done less than a minute apart.
First scan:
![uua-falcon_fluentd-aggregator-1 6 3-ubuntu_LI](https://user-images.githubusercontent.com/11614204/83016147-20174080-a03f-11ea-88f6-0f4c02273281.jpg)

Second scan:
![uua-falcon_fluentd-aggregator-1 6 3-ubuntu_CRITICAL_7_LI](https://user-images.githubusercontent.com/11614204/83016265-4c32c180-a03f-11ea-9458-fcb0a8ec2af1.jpg)

scanner version 0.10.0

CC: @svisagan83

Regards.

**Comment by piyush94** [comment]
From trivy 0.7.0, i can see they are coming from different files in the image, but this information is not available in harbor scan. But, also it's changing between count 4 and 7.
![fa1_LI](https://user-images.githubusercontent.com/11614204/83018571-290a1100-a043-11ea-8b59-42be5044ff5e.jpg)
![fa2](https://user-images.githubusercontent.com/11614204/83018574-2b6c6b00-a043-11ea-8f09-32e78be71f5f.JPG)

CC: @svisagan83

**Comment by danielpacak** [comment]
@piyush94 Thank you for opening this issue. I did check and I can reproduce the "duplicates" issue.

However I cannot reproduced the discrepancy in the number of critical vulnerabilities found by Trivy in short intervals. Could you provide more details whether your trivy.db file is cached and / or is up to date?

Regarding duplicates, Trivy scans each `Gemfile.lock` independently and reports vulnerabilities, if any, as a separate targets in the output report. In your example there are 3 `Gemfile.lock` files. When we map these targets to the Harbor model we somehow loose the context from which `Gemfile.lock` the vulnerable library dependency comes from, but from our stand point it's not a duplicate.

If I append the path to a `Gemfile.lock` to a package name we'd get a noisy report as shown below:

<img width="1536" alt="trivy_targets_in_harbor" src="https://user-images.githubusercontent.com/1322923/83162430-08f15500-a10a-11ea-9c6c-2f43b893dc1f.png">

Originally the Harbor model catered only for OS packages but not application dependencies. What we've done with Trivy is bending a bit the reality, but maybe in the next releases of Harbor we'll extend the model to provide the missing context described above in the Harbor user interface.

**Comment by piyush94** [comment]
@danielpacak Thank you for the info.
Regarding the discrepancy, yesterday, as you can see from my screenshot, Trivy 0.7.0 was showing total count of 7 from 3 files.
But today's scan is matching what you have shared, total count 4 from 2 files, although the image hasn't changed.
Is there any reason for this?

CC: @svisagan83

**Comment by piyush94** [comment]
@danielpacak Seems to be a cache issue.
[fluentd.txt](https://github.com/aquasecurity/harbor-scanner-trivy/files/4697945/fluentd.txt)
[fluentd-cache-cleared.txt](https://github.com/aquasecurity/harbor-scanner-trivy/files/4697947/fluentd-cache-cleared.txt)

**Comment by danielpacak** [comment]
Interesting. The only way I could get 7 critical vulnerabilities is with the previous version of the adapter service, which relies on Trivy v0.6.0. As you might remember in Trivy v0.7.0 we prefer vendor severity, which might justify the discrepancy. Is there any chance that you're running multiple instances of the adapter service, and one of them is still on the previous version?

<img width="1511" alt="trivy_0 6 0" src="https://user-images.githubusercontent.com/1322923/83191331-20453800-a134-11ea-9f5f-e9521b11d559.png">

**Comment by piyush94** [comment]
@danielpacak - I did check our deployment, all the instances are running on v0.10.0. from past 9 days.

**Comment by danielpacak** [comment]
> @danielpacak Seems to be a cache issue, as both scans are with the same DB.
> [fluentd.txt](https://github.com/aquasecurity/harbor-scanner-trivy/files/4697945/fluentd.txt)
> [fluentd-cache-cleared.txt](https://github.com/aquasecurity/harbor-scanner-trivy/files/4697947/fluentd-cache-cleared.txt)

@piyush94 A few more questions so I fully understand what's happening in your environment:
- When you say cache issue, are you referring to `trivy.db` file or `fanal.db` or maybe the latest scan results stored in Harbor DB?
- How did you clean the cache, was it `trivy -c` command?
- Last but not least, after all did cleaning the cache resolve the discrepancy? Or is is still reproducible? I cannot reproduce it on my end.

**Comment by piyush94** [comment]
@danielpacak 
- I am not sure which database, but I was referring to this line in the trivy debug log `DB Schema: 1, Type: 1, UpdatedAt: 2020-05-28 12:10:23.757050823 +0000 UTC`.
- I ran the first scan with the flag `--skip-update` and got total count 7 always. Then I cleared cache using `trivy -c` command.
- After this, I got total count as 4 in the next scans with the flag `--skip-update`.

After observing the discrepancy in Harbor, I did this test with local trivy, not harbor.

**Comment by piyush94** [comment]
Also, i did some more tests now.
![uua-fa163_1](https://user-images.githubusercontent.com/11614204/83258360-c6944a80-a1d3-11ea-95a8-563045b67e8e.JPG)

![fa163_4](https://user-images.githubusercontent.com/11614204/83258365-c8f6a480-a1d3-11ea-8266-13e234b0c0b6.JPG)

![fa163_7](https://user-images.githubusercontent.com/11614204/83258366-c98f3b00-a1d3-11ea-80fe-a2b43eec05ba.JPG)

All three images are same,
![image](https://user-images.githubusercontent.com/11614204/83258442-ea579080-a1d3-11ea-8ce2-e6147d6d6299.png)

Scanner details,
```Scanner:
Name:Trivy
Vendor:Aqua Security
Version:0.7.0
Capabilities
Consumes Mime Types:[application/vnd.oci.image.manifest.v1+json , application/vnd.docker.distribution.manifest.v2+json]
Produces Mime Types:[application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0]
Properties
com.github.aquasecurity.trivy.debugMode:true
com.github.aquasecurity.trivy.ignoreUnfixed:false
com.github.aquasecurity.trivy.insecure:false
com.github.aquasecurity.trivy.severity:UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
com.github.aquasecurity.trivy.skipUpdate:false
com.github.aquasecurity.trivy.vulnType:os,library
harbor.scanner-adapter/scanner-type:os-package-vulnerability
harbor.scanner-adapter/vulnerability-database-next-update-at:2020-05-29T12:16:57Z
harbor.scanner-adapter/vulnerability-database-updated-at:5/29/20, 5:46 AM
org.label-schema.build-date:2020-05-20T12:03:08Z
org.label-schema.vcs:https://github.com/aquasecurity/harbor-scanner-trivy
org.label-schema.vcs-ref:b063d5f467dd9538a7705a720bf99a1177d648ba
org.label-schema.version:0.10.0

**Comment by danielpacak** [comment]
@knqyf263 Looking at the above examples provided by @piyush94 do you have any idea under which conditions we might get such discrepancies? It seems to be reproducible with trivy executable so I bet it's not related to the adapter service.

**Comment by knqyf263** [comment]
@piyush94 Is your image available in public? I couldn't find `ranchercharts/fluentd-aggregator`. Also, it doesn't reproduce in my environment.

**Comment by piyush94** [comment]
@knqyf263 It's this one, https://hub.docker.com/r/ranchercharts/fluentd-aggregator/tags

**Comment by knqyf263** [comment]
@piyush94 Oh, I don't know why I couldn't find the image 😓 I probably did a typo. I'll look into it. Thanks.

**Comment by knqyf263** [comment]
@piyush94 I finally got to know the cause. This is a bug and already fixed in the master branch. I'll release the new version of trivy shortly, then harbor-scanner-trivy is also going to update trivy version. It should be going to fix this problem.

**Comment by piyush94** [comment]
@knqyf263 Which OS and/or packages are affected by this bug?

**Comment by knqyf263** [comment]
@piyush94 This affects the image having multiple lock files, regardless of OS and package. I've released v0.9.0 just before. I'm making sure it works properly now.

**Comment by danielpacak** [comment]
@piyush94 We've just released https://github.com/aquasecurity/harbor-scanner-trivy/releases/tag/v0.11.0 which relies on https://github.com/aquasecurity/trivy/releases/tag/v0.9.0

And we hope that your issue has gone with this new version!

**Comment by piyush94** [comment]
Thanks, @knqyf263 @danielpacak 
The scanner seems to be consistent in results now.

**Comment by knqyf263** [comment]
@piyush94 Thank you for the confirmation!
