### ISSUE TITLE
302 status code when scan isn't ready

### ISSUE THREAD

**Issue by hrist0stoichev** [aquasecurity/harbor-scanner-trivy#125]
I noticed that the API sever returns status code 302 in case the scan is not ready yet but I don’t think 302 is a good status code for that. For one, 302 means `the requested resource resides temporarily under a different URI` which isn’t true by all means (the scan definitely resides under this URI). Yet, the bigger problem is that when the server returns 302, the http client automatically redirects to the url in the Location header and in this case, it is exactly the same URL. What I observed is that the HTTP client makes 10-20 redirects (depending on what I am using) at which point it returns something like `maximum redirections reached`. Does the 302 status code come from some kind of specification or you chose it specifically for some reason? I think a 2xx status code can be better suited for such kind of response. Maybe 204 (no content)?

P.S. I'm talking about [this](https://github.com/aquasecurity/harbor-scanner-trivy/blob/78723e50192c8c38ff780deb7140470dd7d29458/pkg/http/api/v1/handler.go#L175) part of the code.

**Comment by danielpacak** [comment]
The adapter service for Trivy implements Harbor Pluggable Scanner API v1.0, which specifies *302 Found* as a valid response status in such case. See https://github.com/goharbor/pluggable-scanner-spec/blob/master/api/spec/scanner-adapter-openapi-v1.0.yaml#L141

We couldn't find the best fit for such long poll API as there's no industry standard. What's more, 2xx status codes have their own drawbacks, e.g. might require parsing JSON payloads, whereas *302 Found* means that the resource is there but there's no point in unmarshalling until the next request is made. Beyond that, we didn't want to bloat the JSON representation of a vulnerability report with internal processing statuses.

That said, I'm happy to review any proposal for enhancements in Harbor Pluggable Scanner API by opening a PR to this repository https://github.com/goharbor/pluggable-scanner-spec .

In the meantime, in your case, the best is probably to disable automatic redirects in the HTTP client library.

**Comment by hrist0stoichev** [comment]
Thanks for the explanation, you definitely have a point there! Yet, in that case, what do you think about removing the `Location` header? From one side, its kind of strange to have a Redirect response without a `Location` header but, from the other side, it would solve the problem with infinite redirections. Moreover, the specification doesn't include a `Location` header but rather only a `Retry-After` (from which I also don't see a point but that is a different discussion).

Disabling automatic redirects will definitely work for my scenario where I make requests programatically and maybe this is what I'll resort to at the end but it still doesn't work for something like Postman (well, maybe there is some setting in it but you get my point).
