### ISSUE TITLE
Upgrade Trivy Container

### ISSUE THREAD

**Issue by smitphilip** [aquasecurity/harbor-scanner-trivy#164]
I currently have Harbor v2.1.3-b6de84c5 installed on a docker host. There are some issues in the Trivy version (v0.9.2) that gets shipped with Harbor v2.1.3. These issues were addressed in new versions of Trivy. Will it be possible to upgrade the Trivy container only, independent of the other containers?

I see the Harbor installation pulls its images from the goharbor docker hub and the versions are tied to the Harbor versions.

```
$ sudo docker image ls | grep trivy
goharbor/trivy-adapter-photon               v2.1.3              e7896af8b06e        2 months ago        114MB
```

What implications would it have if I were to grab one of the images from the aquasec docker hub (aquasec/harbor-scanner-trivy) and point the docker-compose file there? 

Testing this on a lab server, I had to make a few minor adjustments to the user/group permissions of the directories being mounted. Different UID and GID of the scanner user. Besides this, I haven't run into any issues. Images are being scanned successfully.
Anything I should be aware of? Would this be a production-ready solution?

**Comment by danielpacak** [comment]
👋 @smitphilip Basically it's the same code and the only difference would be UID and GID and base image used in the container image. The Go code is the same. The reason Harbor does not use aquasec/harbor-scanner-trivy image directly is that Harbor required Photon as a base image for its components, whereas we used alpine for this project. Other than that the solution is production ready.

**Comment by smitphilip** [comment]
Awesome! Thank you... Could you elaborate on that base-image requirement from Harbor? Do you see any problems if I run the Harbor stack but with Trivy Adapter container from AquaSec?

**Comment by danielpacak** [comment]
AFAIK the requirement was more for VMware's enterprise registry offering based on Harbor open source. I don't have enough context to compare Photon OS with Alpine OS, but this can be a good question to ask in the Harbor's slack channel.

**Comment by danielpacak** [comment]
@smitphilip I hope I answered your question and I'll proceed closing this issue. Do let us know if there's something we can help with.
