### ISSUE TITLE
Running with client-server mode

### ISSUE THREAD

**Issue by airycanon** [aquasecurity/harbor-scanner-trivy#167]
As https://aquasecurity.github.io/trivy/v0.18.0/modes/client-server said, I need to update vulnerability database in the background, is there a way to do this? 
Thanks for any help.

**Comment by danielpacak** [comment]
Hi @airycanon ! I'm not sure if I understood your question, but this adapter service for Harbor is using Trivy in standalone mode. In this mode Trivy command downloads Trivy DB from GitHub and stores the DB file in a local file system cache. You don't have to download this file manually so long you enable egress to GitHub APIs
