### ISSUE TITLE
DB download required when ip changes

### ISSUE THREAD

**Issue by owninfo-jiang** [aquasecurity/harbor-scanner-trivy#185]
Hi,
We are using trivy in an offline environment. It's required to download DB whenever the scanner ip changes even it's not the first run.
is there any way to skip update ( --skip-update doesn't work)?

**Comment by danielpacak** [comment]
👋 @owninfo-jiang Not sure I understood your question. This adapter service is configurable via environment variables at startup and you are not supposed to pass manually any flags, such as `--skip-update` to trivy executable binary. Instead adjust environment variable values.

For example, set the value of `SCANNER_TRIVY_SKIP_UPDATE` to `false` to instruct Trivy to skip DB updates. This would also require manually mounting DB at file as explained on https://github.com/aquasecurity/harbor-scanner-trivy/tree/v0.21.0#error-database-error---skip-update-cannot-be-specified-on-the-first-run

If you still need help with this issue please provide mode details about installed versions and how you installed it, .e.g. Harbor installer vs Harbor Helm chart.

**Comment by owninfo-jiang** [comment]
How do I set the variable value to escape the update? I installed trivy 0.19.2 by using rpm command.

**Comment by danielpacak** [comment]
> How do I set the variable value to escape the update? I installed trivy 0.19.2 by using rpm command.

I think you are confusing this project, which is just a thin adaptation service between Harbor and Trivy scanner, with [Trivy executable binary](https://github.com/aquasecurity/trivy) project.

You are not supposed to use rpm or any other package manager to deploy Harbor scanner adapter for Trivy. At least we do not support it. The only supported way is to use Docker Compose and Helm chart.

Please consult [Air-Gapped Environment](https://aquasecurity.github.io/trivy/v0.19.2/advanced/air-gap/) section in the official Trivy documentation.
