### ISSUE TITLE
Trivy Scanner scan images found: Context  deadline exceeded

### ISSUE THREAD

**Issue by bad2cat** [aquasecurity/harbor-scanner-trivy#186]
Harbor version: v2.2.2

Trivy Adapter version：v0.18.0

Trivy version：v0.16.0

Add Trivy Scanner，and scan a image found error：timeout context deadline exceeded；Lookup trivy documentation,thers is solution：

https://aquasecurity.github.io/trivy/v0.18.3/faq/

add arguments `--timeout=15m`，but not found a configuration in Harbor Trivy Adapter

**Comment by danielpacak** [comment]
That's a very good point @bad2cat Would you be interested in contributing to add such a configuration setting?

**Comment by bad2cat** [comment]
> That's a very good point @bad2cat Would you be interested in contributing to add such a configuration setting?

ok，i will try

**Comment by prashi2202** [comment]
I had a similar issue with Trivy running on K8S env, basically was not able to scan a large image (100GB) and failed with the following error.

{"exit_code":1,"image_ref":"harbor-core:443/hundredgb/hundredgb@sha256:f658652037766f61ffc68a4fecd3e88ace308f6e6ed7dbeb1956b5031ba968d9","level":"error","msg"
:"Running trivy failed","std_out":"2021-09-29T09:05:35.783Z\t\u001b[33mWARN\u001b[0m\tIncrease --timeout value\n2021-09-29T09:05:35.783Z\t\u001b[31mFATAL\u001
b[0m\tscan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded\n","time":"2021-09-29T09:05:35Z"}

Induced timeout parameter as mentioned below and that seems to have resolved the issue.  Trivy did not reboot and the scan got completed for a 100GB test image.

$ k describe pod harbor-trivy-0
Name:         harbor-trivy-0
Namespace:    vas
Priority:     0
Node:         XXXXXX
Start Time:   Fri, 01 Oct 2021 09:39:21 +0530
Labels:       app=harbor
              chart=harbor
              component=trivy
              controller-revision-hash=harbor-trivy-5cd8f467fd
              heritage=Helm
              release=harbor
              statefulset.kubernetes.io/pod-name=harbor-trivy-0
.
.
.
      TRIVY_TIMEOUT:                       40m    # Added timeout value...
      SCANNER_LOG_LEVEL:                   info
      SCANNER_TRIVY_CACHE_DIR:             /home/scanner/.cache/trivy

**Comment by danielpacak** [comment]
@bad2cat Not sure if you made any progress on that, but since this issue is reported in multiple channels already I decided to give it more priority and implemented it in #191
