### ISSUE TITLE
Unclear how to deploy this on bare-metal harbor/trivy deployment

### ISSUE THREAD

**Issue by distortedsignal** [aquasecurity/harbor-scanner-trivy#210]
It is unclear how to deploy this when harbor and trivy are both deployed in a non-Kubernetized way. I would love to use helm to install this project, but since Trivy and Harbor are both installed on the same host, that's not really possible.

**Comment by py-go** [comment]
If you want to use ```harbor-scanner-trivy``` also in non-Kubernetized way then you can simply follow these steps to integrate the binary version of it:

- Start a Redis DB in your system(**it's kind of prerequisite**).

- Run ```make``` to get the binary version of harbor-scanner-trivy called: ```scanner-trivy```

- Execute the `scanner-trivy` binary to start the `harbor-scanner-trivy `at 8080 port:
`./scanner-trivy
` 
```
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2021-11-22T04:42:40+05:30","version":"dev"}
{"level":"debug","msg":"Current process","pid":404867,"time":"2021-11-22T04:42:40+05:30"}

```

- Now, follow the "_Configure the scanner adapter in the Harbor interface_"  section from the main doc and inside the scanner endpoint just the IP of your system along with 8080 port.


**NOTE:**
If you are getting some error like "certificate signed by unknown authority"  
then you can simply run export SCANNER_TRIVY_INSECURE="true" before running the `make` and execute the binary again.

**Comment by danielpacak** [comment]
Trivy Adapter is usually deployed as a container in Docker Compose project or as pod in Kubernetes cluster with Helm. These options are well document in Harbor documentation.
