### ISSUE TITLE
Can this adapter use the same redis with another trivy in server mode for cache?

### ISSUE THREAD

**Issue by NitroCao** [aquasecurity/harbor-scanner-trivy#218]
Cause the trivy in this adapter runs in standalone mode, we need to run another trivy instance in server mode to integrate trivy into CI/CD. So as the title describes, can these two trivy instances use the same redis instance? In other words, is there any race condition if the two trivy instances use the same redis instance?

BTW, is there any plan to let the adapter run in client mode, so we can increase the speed of scanning?

**Comment by danielpacak** [comment]
This adapter service can use any Redis instance by setting the connection URL with the  `SCANNER_REDIS_URL` environment variable. There should not be any clash with Trivy server, but if that's the case you can always configure key prefix with `SCANNER_STORE_REDIS_NAMESPACE`.

We don't have any plan to switch for a ClientServer mode as we have a local fiesystem cache similar to what Trivy server does.

**Comment by NitroCao** [comment]
I mean if we can use the same cache in redis to speed up scanning?

**Comment by danielpacak** [comment]
> I mean if we can use the same cache in redis to speed up scanning?

It's not possible to reuse the cache managed by Trivy server. This adapter service is using Redis to cache scan reports that are eventually persisted in the Harbor database.
