### ISSUE TITLE
Errors regarding invalid usage due to Trivy 0.24.2 not supporting -version -format json

### ISSUE THREAD

**Issue by cnwaldron** [aquasecurity/harbor-scanner-trivy#222]
**What steps did you take and what happened:**
Just upgraded existing working deployment with new version v0.26.0 with offline scan and skip update enabled. 
[A clear and concise description of what the bug is, what commands you ran, and which actions you performed in Harbor UI.]

1. Initiate a scan in Harbor (v2.4.1)
2. Scan returns results
Log of the harbor-scanner-trivy is full of errors like below:
```
{"error": running trivy; exit status 1: Incorrect Usage. flag provided but not defined: -format\n\nNAME: trivy - .....(rest of the default trivy help output)"...}
```

**What did you expect to happen:**

[To reproduce CVE data quality problems provide a minimal container image with pinned versions or point us to a public registry so we can pull the image down by digest.]
I expect the log to not be full of errors. 

**Anything else you would like to add:**
After looking into the code to see what commands the harbor-scanner-trivy were making to trivy, I think at least one issue is found here: https://github.com/aquasecurity/harbor-scanner-trivy/blob/main/pkg/trivy/wrapper.go#L219

When I ran the same command in a Trivy:0.24.2 I received the same error message regarding `flag provided but not defined: -format`
That command was working in Trivy v0.22.0. 

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Harbor version: v2.4.1
- Harbor Scanner Adapter for Trivy version: v0.26.0
- Harbor installation process ([Installer script][harbor-installer], [Helm chart][harbor-helm], etc.): Helm Chart

[harbor-helm]: https://goharbor.io/docs/2.3.0/install-config/harbor-ha-helm/
[harbor-installer]: https://goharbor.io/docs/2.3.0/install-config/download-installer/

**Comment by danielpacak** [comment]
Nice catch @cnwaldron and thank you for opening this issue! We talked with @knqyf263 and it's a regression in Trivy. To fix it we'll bump up Trivy once new version is available.

**Comment by danielpacak** [comment]
https://github.com/aquasecurity/trivy/pull/1854

**Comment by hasonhai** [comment]
Seems like the issue persist after replace with Trivy v0.25.0.

**Comment by danielpacak** [comment]
Thank you for checking this out @hasonhai I'll have one more proper look into this issue.

**Comment by hasonhai** [comment]
I linked the log of Trivy v0.25.0 here #229
