### ISSUE TITLE
Can I depoly harbor-scanner-trivy on another machine?

### ISSUE THREAD

**Issue by zhuxindong** [aquasecurity/harbor-scanner-trivy#236]
**If I deploy the harbor on machine A, can I deploy the harbor-scanner-trivy  on machine B?**
I try to do it, I just deploy  harbor on machine A and deploy the harbor-scanner-trivy  on machine B.
But it seems like "harbor-scanner-trivy" cannot find the "http://core:8080/v2", obviously , machine B cannot resolve  the dns because machine A and machine B is not in the same network "harbor".
So, how can I specify the habor-core's url  in machine B?

the error message  is like this:
`{"error":"running trivy wrapper: running trivy: exit status 1: 2022-04-28T07:05:23.749Z\t\u001b[35mDEBUG\u001b[0m\tSeverities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL\n2022-04-28T07:05:23.758Z\t\u001b[35mDEBUG\u001b[0m\tcache dir:  /home/scanner/.cache/trivy\n2022-04-28T07:05:23.758Z\t\u001b[35mDEBUG\u001b[0m\tDB Schema: 1, Type: 1, UpdatedAt: 2022-04-28 06:44:29.189923343 +0000 UTC, NextUpdate: 2022-04-28 12:44:29.189923243 +0000 UTC, DownloadedAt: 0001-01-01 00:00:00 +0000 UTC\n2022-04-28T07:05:23.771Z\t\u001b[31mFATAL\u001b[0m\tunable to initialize a scanner:\n    github.com/aquasecurity/trivy/internal/artifact.run\n        /home/circleci/project/internal/artifact/run.go:73\n  - unable to initialize a docker scanner:\n    github.com/aquasecurity/trivy/internal/artifact.dockerScanner\n        /home/circleci/project/internal/artifact/image.go:28\n  - 3 errors occurred:\n\t* unable to inspect the image (core:8080/library/qinglong@sha256:3f396f409c163d87e8cee71cd2a4523933cebe82726489d9e22b37479740111b): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* Get \"http://core:8080/v2/\": dial tcp: lookup core on 140.207.198.6:53: no such host\n\n\n","level":"error","msg":"Scan job failed","scan_job_id":"f759aaca025479d20f55c9c0","time":"2022-04-28T07:05:27Z"}`

**Comment by danielpacak** [comment]
Harbor core communicates with Trivy adapter via HTTP(S) protocol so they can be deployed on separate hosts. Usually we do not provide support for networking issues / config unless it's related to functionality of the adapter service.

**Comment by zhuxindong** [comment]
thanks , but i found that you had said "Make sure that all Harbor services as well as adapter service are in the same Docker network and can see each other" in https://github.com/aquasecurity/harbor-scanner-trivy/issues/73#issuecomment-577765122.
Is that mean the Harbor core and Trivy adapter aor must in the same docker network? I don't find any configuration in Trivy adapter to specify the habor-core's url

**Comment by danielpacak** [comment]
Harbor registry URL is not configurable, but is passed to Trivy Adapter in [ScanRequest](https://github.com/aquasecurity/harbor-scanner-trivy/blob/e0160bc153644fa65eef9c5c0dd91417d1eb18d0/pkg/harbor/model.go#L63) payload.

**Comment by zhuxindong** [comment]
thank you very much, I have a very large harbor cluster, and for some reasons, i must deploy the Trivy Adapter in another machine,since the Harbor registry URL is not configurable , it fail :(
