### ISSUE TITLE
how  to give paramter "--offline-scan" to trivy

### ISSUE THREAD

**Issue by zhuxindong** [aquasecurity/harbor-scanner-trivy#237]
hello, i want to use harbor-scanner-trivy in Air-Gapped Environment, how can i give the paramter "--offline-scan"  to trivy?

**Comment by danielpacak** [comment]
https://github.com/aquasecurity/harbor-scanner-trivy#configuration for the rescue. There is the SCANNER_TRIVY_OFFLINE_SCAN environment variable.
