### ISSUE TITLE
harbor integration trivy report Unhealthy

### ISSUE THREAD

**Issue by kycheng** [aquasecurity/harbor-scanner-trivy#341]
**What steps did you take and what happened:**

Deploy harbor through harbor-helm, set the resource to 2c4g, and enable trivy at the same time, and found that the integrated trivy is in an unhealthy state.

Through the harbor core log, you can see that the call to the trivy API times out.

Then call the corresponding API in the trivy pod and find that the request time is too long.

![image](https://github.com/aquasecurity/harbor-scanner-trivy/assets/22126779/245757a1-f7af-4a02-a5fe-862902ef0138)

**What did you expect to happen:**

can be trivy can return quickly.

**Anything else you would like to add:**

By adding logs, the slowest location is when getting the trivy version.
https://github.com/aquasecurity/harbor-scanner-trivy/blob/4b361fb1f8dfc3599aabd827f532c067632729df/pkg/http/api/v1/handler.go#L233-L236

and

https://github.com/aquasecurity/harbor-scanner-trivy/blob/4b361fb1f8dfc3599aabd827f532c067632729df/pkg/trivy/wrapper.go#L216-L228

I guess it has something to do with the offline data package in my pod, but it is still slow after I delete trivy.db.

befor:
![image](https://github.com/aquasecurity/harbor-scanner-trivy/assets/22126779/074075a7-ce39-4a98-be28-53617c1035d2)
after
![image](https://github.com/aquasecurity/harbor-scanner-trivy/assets/22126779/216ef899-1231-4c0f-8d29-f1efe5d7cdab)

only version:
![image](https://github.com/aquasecurity/harbor-scanner-trivy/assets/22126779/e33345b7-b448-4519-be10-b5599f43f6fe)

I tried our previous version and this command returned very fast.
![image](https://github.com/aquasecurity/harbor-scanner-trivy/assets/22126779/200e6596-6932-40f5-8d70-8ef7b9ade4fd)

**Environment:**

- Harbor version: 2.6.4
- Harbor Scanner Adapter for Trivy version: 0.37.2
- Harbor installation process ([Installer script][harbor-installer], [Helm chart][harbor-helm], etc.): Helm chart

[harbor-helm]: https://goharbor.io/docs/2.3.0/install-config/harbor-ha-helm/
[harbor-installer]: https://goharbor.io/docs/2.3.0/install-config/download-installer/

**Comment by SimonWoidig** [comment]
Can confirm - bumped into this issue aswell.

**Comment by knqyf263** [comment]
The latest Trivy returns the version very fast. Could you bump the adapter version and try it again?

```
/usr/bin/time $ trivy --version
Version: 0.51.1
        0.28 real         0.39 user         0.03 sys
```

**Comment by SimonWoidig** [comment]
Here is the output:
```
time trivy --version
Version: 0.50.1

real    0m3.889s
user    0m3.412s
sys     0m0.220s
```

Will try it with the newer version. Thank you.

**Comment by SimonWoidig** [comment]
Well I am using the Bitnami chart and there is no tag with a newer version of Trivy. I will create an issue there and add a link to this issue.
You can close this issue I guess.
Thank you again!

**Comment by knqyf263** [comment]
Thanks. Please feel free to reopen it if you still face the same problem with the latest version of Trivy.
