### ISSUE TITLE
the helm repo has a bogus release with version 0.31.0

### ISSUE THREAD

**Issue by Tyrael** [aquasecurity/harbor-scanner-trivy#428]
**What steps did you take and what happened:**

```
helm repo add aqua https://aquasecurity.github.io/helm-charts
helm pull aqua/harbor-scanner-trivy

Error: failed to fetch https://github.com/aquasecurity/helm-charts/releases/download/harbor-scanner-trivy-0.31.0/harbor-scanner-trivy-0.31.0.tgz : 404 Not Found
```

**What did you expect to happen:**

helm successfully fetching the latest version(v0.30.21)

**Comment by Tyrael** [comment]
it looks this is caused by a typo for a past release:
https://github.com/aquasecurity/harbor-scanner-trivy/pull/269/commits/5e4d38b70c6b7dd7ee2b06e062b0ea34bca20a4d
0.30.1 vs 0.31.0

**Comment by Tyrael** [comment]
cc @chen-keinan

**Comment by Tyrael** [comment]
I think deleting this release (which is already mostly purged from the changelogs, release history, etc.) and rerunning the `publish-helm-chart` pipeline would solve the issue:
https://github.com/aquasecurity/harbor-scanner-trivy/releases/tag/v0.30.1

**Comment by Tyrael** [comment]
@chen-keinan any update on this?

**Comment by chen-keinan** [comment]
@Tyrael should be fixed now , delete you local helm cache for this repo
run 
help report update/add to create index file again and it should work.
