### ISSUE TITLE
Ability to customize trivy scan

### ISSUE THREAD

**Issue by skurtzemann** [aquasecurity/harbor-scanner-trivy#63]
It could be nice if we can customized some parameters of the `trivy` scan :
1.  severities of vulnerabilities to be displayed
2. ability to display only fixed vulnerabilities

My use case is to provide 
- a "light" scanner configure with `CRITICAL` and `HIGH` severities and only with fixed vulns
- a "hard" scanner which reports all vulns

---
As scanner wraps `trivy` under the hood, we could simply use `trivy` env variables to do this :
- `TRIVY_SEVERITY` to set severities
- `TRIVY_IGNORE_UNFIXED` to display fixed vulnerabilities

Or introducing new env variables for scanner like for example ?
- `SCANNER_TRIVY_SEVERITY`
- `SCANNER_TRIVY_IGNORE_UNFIXED`

What do you think about this proposition ?

**Comment by danielpacak** [comment]
> It could be nice if we can customized some parameters of the `trivy` scan :
> 
> 1. severities of vulnerabilities to be displayed
> 2. ability to display only fixed vulnerabilities
> 
> My use case is to provide
> 
> * a "light" scanner configure with `CRITICAL` and `HIGH` severities and only with fixed vulns
> * a "hard" scanner which reports all vulns
> 
> As scanner wraps `trivy` under the hood, we could simply use `trivy` env variables to do this :
> 
> * `TRIVY_SEVERITY` to set severities
> * `TRIVY_IGNORE_UNFIXED` to display fixed vulnerabilities
> 
> Or introducing new env variables for scanner like for example ?
> 
> * `SCANNER_TRIVY_SEVERITY`
> * `SCANNER_TRIVY_IGNORE_UNFIXED`
> 
> What do you think about this proposition ?

I think this proposal makes perfect sense. To be consistent with existing configs I'd go for `SCANNER_TRIVY_SEVERITY` and `SCANNER_TRIVY_IGNORE_UNFIXED` envs.

Are you going to work on this one? If yes I'll assign to you. Thanks!

**Comment by skurtzemann** [comment]
> > It could be nice if we can customized some parameters of the `trivy` scan :
> > 
> > 1. severities of vulnerabilities to be displayed
> > 2. ability to display only fixed vulnerabilities
> > 
> > My use case is to provide
> > 
> > * a "light" scanner configure with `CRITICAL` and `HIGH` severities and only with fixed vulns
> > * a "hard" scanner which reports all vulns
> > 
> > As scanner wraps `trivy` under the hood, we could simply use `trivy` env variables to do this :
> > 
> > * `TRIVY_SEVERITY` to set severities
> > * `TRIVY_IGNORE_UNFIXED` to display fixed vulnerabilities
> > 
> > Or introducing new env variables for scanner like for example ?
> > 
> > * `SCANNER_TRIVY_SEVERITY`
> > * `SCANNER_TRIVY_IGNORE_UNFIXED`
> > 
> > What do you think about this proposition ?
> 
> I think this proposal makes perfect sense. To be consistent with existing configs I'd go for `SCANNER_TRIVY_SEVERITY` and `SCANNER_TRIVY_IGNORE_UNFIXED` envs.
> 
> Are you going to work on this one? If yes I'll assign to you. Thanks!

Ok for your responses. Yes I'll work on this proposal :)

**Comment by danielpacak** [comment]
Resolved in #64
