### ISSUE TITLE
Helm chart issues with persistent volumes

### ISSUE THREAD

**Issue by svanschie** [aquasecurity/harbor-scanner-trivy#69]
When deploying in Kubernetes using the Helm chart, there are some issues with the configuration of persistent volumes.

If you're using persistent volumes, the .cache directory is not writable by uid 1000. If you disable persistent volumes, it's also not writable due to it not being a separate volume and the root filesystem being read only.

It would also be nice to use the default storage class by default like most Helm charts do.

**Comment by danielpacak** [comment]
Hi @svanschie . Thank you for trying out Trivy adapter and opening the issue.
Just for my understanding, you mentioned .cache directory that's not writable. Are you referring to /home/scanner/.cache directory? I believe this one should be writable by uid 1000 - as its home directory.

**Comment by svanschie** [comment]
Hi @danielpacak, yes I meant the /home/scanner/.cache directory. For me this wasn't writable by uid 1000 by default. By setting the fsGroup=1000 on pod level, this resolved the issue. I'm not sure, but perhaps this depends on the storage driver used for persistent storage, we are using Portworx. Most Helm charts seem to use fsGroup by default when using persistent volumes.

Perhaps it would be better to make the securityContext (both on pod and container level) fully configurable through the values file and setting the currently used values as defaults there. What do you think?

**Comment by danielpacak** [comment]
> Hi @danielpacak, yes I meant the /home/scanner/.cache directory. For me this wasn't writable by uid 1000 by default. By setting the fsGroup=1000 on pod level, this resolved the issue. I'm not sure, but perhaps this depends on the storage driver used for persistent storage, we are using Portworx. Most Helm charts seem to use fsGroup by default when using persistent volumes.
> 
> Perhaps it would be better to make the securityContext (both on pod and container level) fully configurable through the values file and setting the currently used values as defaults there. What do you think?

Got your point. Let's set fsGroup to resolve your main issue in the first run. And I'm okey with making securityContext configurable with Helm values.

**Comment by danielpacak** [comment]
Resolved by #70
