### ISSUE TITLE
Can I use trivy client --remote on trivy deployed in harbor?

### ISSUE THREAD

**Issue by vzanlnx** [aquasecurity/harbor-scanner-trivy#76]
I just deployed Trivy with my harbor environment and everything seems to be working fine in the portal, except for one thing.

I'm trying to scan a local image using the trivy server that was deployed in my harbor server.

```
# trivy client --remote https://harbor-trivy.mydomain:8443 image:tag

2020-02-19T18:00:00.291Z	FATAL	error in image scan: failed to scan the image:
failed to detect vulnerabilities: failed to detect vulnerabilities via RPC:
twirp error bad_route: Error from intermediary with HTTP status code 404 "Not Found"
```

The address harbor-trivy.mydomain is a cname I created that points to the load balancer helm created.

I installed with the following params:
```
helm install harbor-scanner-trivy ./helm/harbor-scanner-trivy \
               --namespace harbor-test \
               --set service.port=8443 \
               --set scanner.api.tlsEnabled=true \
               --set scanner.api.tlsCertificate="`cat tls.crt`" \
               --set scanner.api.tlsKey="`cat tls.key`"
````

Can you pls tell me if I am doing something wrong or if this function (trivy client --remote) is not available for this kind of deployment?

**Comment by danielpacak** [comment]
Hi @vzanlnx ! Thank you for the question. It's a good one.

Trivy [client/server mode](https://github.com/aquasecurity/trivy#client--server) and [Harbor scanner adapter](https://github.com/goharbor/pluggable-scanner-spec) for Trivy are two different things.

To some extent they are similar, but have different clients and communication protocols. harbor-scanner-trivy exposes the REST API which is consumed by Harbor core services, whereas Trivy server exposes gRPC endpoint consumable by Trivy client.

That said, the following command won't work:

```
$ trivy client --remote https://harbor-trivy.mydomain:8443 image:tag
```

I hope it's clear now.

**Comment by knqyf263** [comment]
It's not gRPC, but [twirp](https://github.com/twitchtv/twirp) over ProtocolBuffer. Anyway, Trivy client is designed to send a request to Trivy server launched by `$ trivy server` exposing twirp endpoint. As Daniel said, harbor-scanner-trivy is intended to take a request from Harbor core services. They are different servers.

**Comment by vzanlnx** [comment]
Thanks for your quick answer on this, much appreciated.

So, is there a supported way to deploy a trivy server on k8s in order to use this way I want? 

So I may have two trivy deployments in my k8s cluster, one for harbor and another one for use with `client --remote`. Is there some doc on this? I didn`t find one.

let me know if my question is not clear.

thanks!

**Comment by danielpacak** [comment]
@vzanlnx Currently we do not support K8S deployment descriptor for Trivy server, but I believe that you can create one relatively easy with our official `docker.io/aquasec/trivy:0.4.4` Docker image. Just run a Pod with the server command and args. If you expose it with K8S Service you should be able to connect to it with Trivy client from outside of the cluster.

We've created a follow up issue #77 to consider whether harbor-scanner-trivy should expose twirp endpoint and serve both Harbor and Trivy clients. Feel free to vote on that one and provide more details about your use case there.

**Comment by danielpacak** [comment]
Closing this one as we've answered the original question. There's a follow up created #77
