### ISSUE TITLE
Got permission error when the db file was copyed from others

### ISSUE THREAD

**Issue by heww** [aquasecurity/harbor-scanner-trivy#98]
1. Install trivy with `skip_update` 
2. Copy trivy.db from offline to `/data/trivy-adapter/trivy/db/trivy.db`
3. Scan image
4. Got error `error in vulnerability DB initialize: failed to open db: open /home/scanner/.cache/trivy/db/trivy.db: permission denied` but the trivy.db permission is `-rwxr-xr-x 1 root  root  128770048 Apr 10 01:00 trivy.db`

**Comment by danielpacak** [comment]
Hey @heww How do you run/install the Trivy adapter service?
- Is it with Docker or Helm?
- Docker on Linux or Docker for Mac?
- Are you using the official image that we publish to Docker Hub `docker.io/aquasec/harbor-scanner-trivy:0.8.0` or the one based on PhotonOS 2.0, i.e. `goharbor/trivy-adapter-photon:dev`?
- What's the permission of `/data/trivy-adapter/trivy/db/trivy.db`?

The adapter service is run as non-privileged user `1000` or `10000` depending on whether you use  `docker.io/aquasec/harbor-scanner-trivy:0.8.0` or `goharbor/trivy-adapter-photon:dev`. (BTW, I'll make it consistent, but it's not that relevant anyway.)

If you run docker with volume mounts as a root user, trivy adapter doesn't have enough privileges to read/write to/from mount location `/home/scanner/.cache/trivy/db/trivy.db`

So what's missing is some kind of:

```
$ chown -R 1000:1000 /data/trivy-adapter/
$ chown -R 10000:10000 /data/trivy-adapter
```

or

```
$ chmod a+rwx /data/trivy-adapter
```

**Comment by danielpacak** [comment]
Cannot reproduce this one. Please reopen if the problem persists.

**Comment by sidarmawan** [comment]
Thank you, work for me.
